name: Github Actions Linter
on:
  pull_request: 
    branches: [develop, staging, master]
    types: [opened, synchronize]
  release:
    types: [published]

jobs:
  Action-lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Linter
        run: brew install actionlint
      - name: Execute Linter
        run: actionlint
